'use babel';

export const LOAD_WORKSPACES = 'LOAD_WORKSPACES';
export const SELECT_WORKSPACE = 'SELECT_WORKSPACE';
export const EDIT_FILE = 'EDIT_FILE';
export const OPEN_TERMINAL = 'OPEN_TERMINAL';
export const TOGGLE_PROJECT = 'TOGGLE_PROJECT';
export const TOGGLE_DIRECTORY = 'TOGGLE_DIRECTORY';
export const EXECUTE_COMMAND = 'EXECUTE_COMMAND';
export const EXECUTE_COMMAND_FAILED = 'EXECUTE_COMMAND_FAILED';
export const EXECUTE_COMMAND_SUCCESS = 'EXECUTE_COMMAND_SUCCESS';
export const EXECUTE_COMMAND_PROGRESS = 'EXECUTE_COMMAND_PROGRESS';
export const KILL_COMMAND = 'KILL_COMMAND';
export const RESIZE_RIGHT_PANEL = 'RESIZE_RIGHT_PANEL';
export const TOGGLE_SECTION = 'TOGGLE_SECTION';
export const LOAD_REPOSITORY = 'LOAD_REPOSITORY';
